# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and Build
# Trigger the workflow on push or pull request events ONLY FOR THE MAIN BRANCH
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "siqui" ]

# Set permissions for the workflow to read contents of the repository(very basic)
permissions: 
  contents: read

# What the worflow must execute when triggered
jobs:
  #Renamed build-->"text-and-build"
  test-and-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    #Check the Coverage threshold - if the coverage is below 70% the build will fail
    - name: Check coverage threshold
      run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "Coverage is $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Coverage below threshold"
            exit 1
          fi
    # Run the complexity analysis with eslint
    - name: Run complexity analysis
      run: npm run lint
    # Run SonarQube scan
    - name: SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=conduit-realworld-django \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 



    
