# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and Build
# Trigger the workflow on push or pull request events ONLY FOR THE MAIN BRANCH
on:
  push:
    branches: [ "main" ]

# Set permissions for the workflow to read contents of the repository(very basic)
permissions: 
  contents: read

# What the worflow must execute when triggered
jobs:
  #Renamed build-->"text-and-build"
  test-and-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.7"
    - name: Install dependencies
      working-directory: django-realworld-example-app-master
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Run tests with coverage
      working-directory: django-realworld-example-app-master
      env:
        DJANGO_SETTINGS_MODULE: conduit.settings
      run: |
        coverage run -m pytest
        coverage xml
    #Check the Coverage threshold - if the coverage is below 70% the build will fail
    - name: Check coverage threshold
      working-directory: django-realworld-example-app-master
      env:
        DJANGO_SETTINGS_MODULE: conduit.settings
      run: |
          COVERAGE=$(coverage report | tail -1 | awk '{print $NF}' | tr -d '%')
          echo "Coverage is $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Coverage below threshold"
            exit 1
          fi
    - name: Run tests with coverage
      run: |
        pip install coverage
        coverage run -m pytest
        coverage xml
    # Run the complexity analysis with eslint
    - name: Lint
      run: flake8 .
    # Run SonarQube Scanner
    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=conduit-realworld-django
          -Dsonar.projectKey=Pablokill2004_Ing.-de-Software---Proyecto
   
   
            



    
